-- Transformed for Aurora DSQL compatibility
-- Generated by aurora-dsql-prisma migrate
--
-- Changes applied:
--   - Each statement wrapped in BEGIN/COMMIT (DSQL requires one DDL per transaction)
--   - CREATE INDEX converted to CREATE INDEX ASYNC (DSQL requires async index creation)
--   - Foreign key constraints removed (DSQL requires application-layer referential integrity use relationMode = "prisma")
--
-- CreateTable
BEGIN;
CREATE TABLE "orders" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "product" TEXT NOT NULL,
    "quantity" INTEGER NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'pending',
    "region" TEXT NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "orders_pkey" PRIMARY KEY ("id")
);
COMMIT;

-- CreateTable
BEGIN;
CREATE TABLE "order_items" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "order_id" UUID NOT NULL,
    "name" TEXT NOT NULL,
    "price" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "order_items_pkey" PRIMARY KEY ("id")
);
COMMIT;

-- CreateIndex
BEGIN;
CREATE INDEX ASYNC "order_items_order_id_idx" ON "order_items"("order_id");
COMMIT;
